### ISSUE TITLE
Some slight issues...

### ISSUE THREAD

**Issue by taylor1324** [finchMFG/finchmfg.github.io#1]
Hey :)

Love your portfolio, good tip though is to make sure all pages are complete before going live, like your contact page doesn't exist

**Comment by finchMFG** [comment]
Hey there! Cheers for the kind words!

I'm still trying to make a good design overall but have been caught between some pretty large projects that are eating at my time. I'll probably put a full version out next week though.

It's pretty neat that you're a dev! :)
